# Is the plugin enabled?
enabled: true

# Should EMF fish only be given during a competition?
fish-only-in-competition: false

# Should a database store data about fish such as how many have been caught and the first to catch it.
# Setting to false will disable it. In a future update this will have a deeper meaning and purpose.
database: true

# When dropping tool items (e.g. fishing rod) should they be dropped with a random durability
# instead of always full durability?
random-durability: true

# Should the plugin hook into vault economy? Having this disabled will only disable /emf shop.
enable-economy: true

# For customizing the /emf shop GUI
gui:
  # Fills the empty slots of a normal /emf shop
  filler: GRAY_STAINED_GLASS_PANE
  # Fills the empty slots of /emf shop when there's an error (i.e. the player trying to sell nothing)
  filler-error: RED_STAINED_GLASS_PANE
  # The item for the player to click to sell their fish
  sell-item: GOLD_INGOT
  # The item for the player to click to confirm selling their fish
  sell-item-confirm: GOLD_BLOCK
  # The item shown to the player when an error occurs (i.e. trying to sell nothing of value)
  sell-item-error: REDSTONE_BLOCK
  # How many rows the selling area of the GUI should be (max 5, min 1)
  size: 3
  # Should the items be dropped(false) or sold(true) when a player exits an inventory?
  sell-over-drop: false



competitions:

  # When should competitions run?
  # It will use server's local timezone using a 24hour time format
  times:
    - "00:00" # midnight
    - "06:00"
    - "12:00" # midday
    - "18:00"

  # The days for the competitions to run, use integers to represent the day
  days:
    - 2 # Monday
    - 3 # Tuesday
    - 4 # Wednesday
    - 5 # Thursday
    - 6 # Friday
    - 7 # Saturday
    - 1 # Sunday

  # How long should the competition go on for? (In minutes)
  duration: 10

  # What colour should the bossbar cooldown be? (values can be found here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/boss/BarColor.html)
  # Set the text and text colour above the bossbar in messages.yml
  bossbar-colour: GREEN

  winnings:
    1:
      # Commands are run by the console, it's advised to change these before releasing your server.
      - "COMMAND:give {player} diamond 5"
      - "MESSAGE:&aCongratulations for coming 1st!"
      # Can't contain decimals.
      - "MONEY:5000"
      # formatted as "effect_name,amplifier,duration", view a list of effects: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/potion/PotionEffectType.html
      - "EFFECT:SPEED,2,5"
      - "ITEM:DIAMOND,2"
    2:
      - "ITEM:DIAMOND,1"
      - "MESSAGE:&bCongratulations for coming 2nd!"
      - "MONEY:2500"
    3:
      - "EFFECT:SPEED,1,5"
      - "MESSAGE:&eCongratulations for coming 3rd!"
      - "MONEY:1000"
  # Add as many more places as you need

  # This is the minimum needed amount of players for an automatic competition to start.
  minimum-players: 5

# Should broadcasted catches (defined in rarities.yml) only be shown to players holding fishing rods?
broadcast-only-rods: true

# Uncomment the below section to enable this feature. It sets the plugin to only give custom fish when users are
# in a list of set defined regions (this requires the worldguard/redprotect plugin). EvenMoreFish automatically
# detects your protection plugin so it's important you don't run both at once. Note- Changing this value requires
# a SERVER RESTART NOT A RELOAD.
#allowed-regions:
#  - "fishing"


# ATTENTION ATTENTION ATTENTION
# DO NOT EDIT THIS VALUE UNLESS YOU'RE UPDATING THE CONFIG.
config-version: 5