name: EvenMoreFish
author: Oheers
version: 1.1.1
main: com.oheers.fish.EvenMoreFish
api-version: 1.16
depend: [Vault]
softdepend: [WorldGuard, PlaceholderAPI, RedProtect]

commands:
  evenmorefish:
    usage: /<command> [name]
    aliases: [emf]